using System.Text;
using System.Text.Json;

namespace HideMyEmailGenerator.Services;

public sealed class HideMyEmailService : IAsyncDisposable
{
    private const string BaseUrlV1 = "https://p68-maildomainws.icloud.com/v1/hme";
    private const string BaseUrlV2 = "https://p68-maildomainws.icloud.com/v2/hme";
    
    private readonly HttpClient _httpClient;
    private readonly Dictionary<string, string> _params = new()
    {
        { "clientBuildNumber", "2413Project28" },
        { "clientMasteringNumber", "2413B20" },
        { "clientId", "" },
        { "dsid", "" }
    };

    public HideMyEmailService(string cookies, string label = "rtuna's gen")
    {
        Label = label;
        _httpClient = CreateHttpClient(cookies?.Trim() ?? string.Empty);
    }

    public string Label { get; }

    private static HttpClient CreateHttpClient(string cookies)
    {
        var client = new HttpClient { Timeout = TimeSpan.FromSeconds(10) };
        client.DefaultRequestHeaders.Add("Connection", "keep-alive");
        client.DefaultRequestHeaders.Add("Pragma", "no-cache");
        client.DefaultRequestHeaders.Add("Cache-Control", "no-cache");
        client.DefaultRequestHeaders.Add("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36");
        client.DefaultRequestHeaders.Add("Accept", "*/*");
        client.DefaultRequestHeaders.Add("Origin", "https://www.icloud.com");
        client.DefaultRequestHeaders.Add("Referer", "https://www.icloud.com/");
        if (!string.IsNullOrWhiteSpace(cookies))
        {
            client.DefaultRequestHeaders.Add("Cookie", cookies);
        }
        return client;
    }

    public async Task<Dictionary<string, object>?> GenerateEmailAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            var url = BuildUrl(BaseUrlV1, "generate");
            var content = new StringContent("{\"langCode\": \"en-us\"}", Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync(url, content, cancellationToken);
            var json = await response.Content.ReadAsStringAsync(cancellationToken);
            return JsonSerializer.Deserialize<Dictionary<string, object>>(json);
        }
        catch (Exception ex) when (ex is TaskCanceledException or HttpRequestException)
        {
            return new Dictionary<string, object> { { "error", 1 }, { "reason", ex.Message } };
        }
    }

    public async Task<Dictionary<string, object>?> ReserveEmailAsync(string email, CancellationToken cancellationToken = default)
    {
        try
        {
            var url = BuildUrl(BaseUrlV1, "reserve");
            var payload = new { hme = email, label = Label, note = "Generated by rtuna's iCloud email generator" };
            var content = new StringContent(JsonSerializer.Serialize(payload), Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync(url, content, cancellationToken);
            var json = await response.Content.ReadAsStringAsync(cancellationToken);
            return JsonSerializer.Deserialize<Dictionary<string, object>>(json);
        }
        catch (Exception ex) when (ex is TaskCanceledException or HttpRequestException)
        {
            return new Dictionary<string, object> { { "error", 1 }, { "reason", ex.Message } };
        }
    }

    public async Task<Dictionary<string, object>?> ListEmailAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            var url = BuildUrl(BaseUrlV2, "list");
            var response = await _httpClient.GetAsync(url, cancellationToken);
            var json = await response.Content.ReadAsStringAsync(cancellationToken);
            return JsonSerializer.Deserialize<Dictionary<string, object>>(json);
        }
        catch (Exception ex) when (ex is TaskCanceledException or HttpRequestException)
        {
            return new Dictionary<string, object> { { "error", 1 }, { "reason", ex.Message } };
        }
    }

    private string BuildUrl(string baseUrl, string endpoint)
    {
        var query = string.Join("&", _params.Select(p => $"{p.Key}={Uri.EscapeDataString(p.Value)}"));
        return $"{baseUrl}/{endpoint}?{query}";
    }

    public ValueTask DisposeAsync()
    {
        _httpClient.Dispose();
        return ValueTask.CompletedTask;
    }
}
